### PR TITLE
update vcflib submodule

### PR DESCRIPTION
**Pull request by DonFreed**

### CODE REVIEW

**Comment by DonFreed** [comment]
Fixes #8

**Comment by yaningyang** [comment]
Thank you so much. But I encountered a new problem.
1. I use the VCF file generated by sniffles as both base and comparison.
```hap_eval -r ~/data/genome/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -b HG002_sniffles.vcf -c HG002_sniffles.vcf```

Prompt the error:
ValueError: ("could not convert string to float: 'None'", 'chrM\t1\tSniffles2.DUP.37S18\tN\t<DUP>\t59\tPASS\tPRECISE;SVTYPE=DUP;SVLEN=16569;END= 16570;SUPPORT=734;COVERAGE=None,None,896,None,None;STRAND=+-;STDEV_LEN=2.531;STDEV_POS=0.223\tGT:GQ:DR:DV\t./.:0:0:0' )

2. I use the VCF file generated by cuteSV as both base and comparison.
```hap_eval -r ~/data/genome/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -b HG002_cuteSV_exclude.vcf -c HG002_cuteSV_exclude.vcf```
Counter()
precision 0.0 recall 0.0 f1 0.0

The calculation results are all 0

**Comment by DonFreed** [comment]
For the first problem, please try the workaround in #10.

**Comment by DonFreed** [comment]
For the second problem, could you please share a small subset of the cuteSV VCF (the header and maybe 10 data lines) and I will take a look.

**Pull request merged**
